{% if helpers.exists('OPNsense.phpipamagent.general') %}
<?php
// Autogenerated - do not edit
// Fixed settings
$config['type'] = "mysql";
$config['method'] 	= "fping";
$config['pingpath'] = "/usr/local/sbin/fping";
$config['nonthreaded'] = false;
$config['sendmail'] = false;

// Settings from configuration page
$config['db']['host'] = "{{ OPNsense.phpipamagent.general.DBHost|default("") }}";
$config['db']['user'] = "{{ OPNsense.phpipamagent.general.DBUser|default("") }}";
$config['db']['pass'] = "{{ OPNsense.phpipamagent.general.DBPass|default("") }}";
$config['db']['name'] = "{{ OPNsense.phpipamagent.general.DBName|default("") }}";
$config['db']['port'] = {{ OPNsense.phpipamagent.general.DBPort|default("") }};
$config['key'] = "{{ OPNsense.phpipamagent.general.AgentCode|default("") }}";
$config['threads']  = {{ OPNsense.phpipamagent.general.Threads|default("") }};
$config['reset_autodiscover_addresses'] = {{ OPNsense.phpipamagent.general.ResetAutodiscover|default("") }};
$config['remove_inactive_dhcp']         = {{ OPNsense.phpipamagent.general.RemoveInactiveDHCP|default("") }};;

// SSL Stuff
$config['db']['ssl']        = false;
$config['db']['ssl_key']    = '/path/to/cert.key';
$config['db']['ssl_cert']   = '/path/to/cert.crt';
$config['db']['ssl_ca']     = '/path/to/ca.crt';
$config['db']['ssl_capath'] = '/path/to/ca_certs';
$config['db']['ssl_cipher'] = 'DHE-RSA-AES256-SHA:AES128-SHA';
$config['db']['ssl_verify'] = true; 
{% endif %}
