{% if helpers.exists('OPNsense.phpipamagent.general') %}
<?php
// Autogenerated - do not edit
// Fixed settings
$config['type'] = "mysql";
$config['method'] 	= "fping";
$config['pingpath'] = "/usr/local/sbin/fping";
$config['nonthreaded'] = false;
$config['sendmail'] = false;

// Settings from configuration page
$config['db']['host'] = "{{ OPNsense.phpipamagent.general.DBHost|default("") }}";
$config['db']['user'] = "{{ OPNsense.phpipamagent.general.DBUser|default("") }}";
$config['db']['pass'] = "{{ OPNsense.phpipamagent.general.DBPass|default("") }}";
$config['db']['name'] = "{{ OPNsense.phpipamagent.general.DBName|default("") }}";
$config['db']['port'] = {{ OPNsense.phpipamagent.general.DBPort|default("") }};
$config['key'] = "{{ OPNsense.phpipamagent.general.AgentCode|default("") }}";
$config['threads']  = {{ OPNsense.phpipamagent.general.Threads|default("") }};
$config['reset_autodiscover_addresses'] = {{ OPNsense.phpipamagent.general.ResetAutodiscover|default(0) }};
$config['remove_inactive_dhcp']         = {{ OPNsense.phpipamagent.general.RemoveInactiveDHCP|default(0) }};

// SSL Stuff
$config['db']['ssl']        = {{ OPNsense.phpipamagent.general.SSL|default(0) }};
{% if OPNsense.phpipamagent.general.SSL|default(0) == '1' %}
$config['db']['ssl_key']    = '/usr/local/etc/phpipamagent/server.key';
$config['db']['ssl_cert']   = '/usr/local/etc/phpipamagent/server.crt';
$config['db']['ssl_ca']     = '/usr/local/etc/phpipamagent/ca.crt';
{% endif %}
$config['db']['ssl_cipher'] = '{{ OPNsense.phpipamagent.general.SSLCipher|default("DHE-RSA-AES256-SHA:AES128-SHA") }}';
$config['db']['ssl_verify'] = {{ OPNsense.phpipamagent.general.SSLVerify|default(0) }}; 
{% endif %}
